version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    env_file:
      - .env
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${NODE_FORWARD_PORT}:${NODE_PORT}"
